name: Build and Release

# Allow the workflow to write repository contents (needed to create releases and commit version changes)
permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Extract version from tag
      id: version
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Extracted version: $VERSION"

    - name: Update pom.xml version
      run: |
        mvn versions:set -DnewVersion=${{ steps.version.outputs.VERSION }}
        mvn versions:commit

    - name: Update plugin.yml version
      run: |
        sed -i "s/version: '.*'/version: '${{ steps.version.outputs.VERSION }}'/" src/main/resources/plugin.yml

    - name: Build with Maven
      run: mvn clean package

    - name: Get artifact name
      id: artifact
      run: |
        ARTIFACT=$(ls target/*.jar | grep -v original)
        echo "ARTIFACT=$ARTIFACT" >> $GITHUB_OUTPUT
        echo "JAR_NAME=$(basename $ARTIFACT)" >> $GITHUB_OUTPUT

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ steps.artifact.outputs.ARTIFACT }}
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit version changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add pom.xml src/main/resources/plugin.yml
        git diff --staged --quiet || git commit -m "chore: bump version to ${{ steps.version.outputs.VERSION }}"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
